//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CORPURSAC\\SQLEXPRESS;Initial Catalog=BD_SIAC_TERAH;Integrated Securit" +
            "y=True")]
        public string BD_SIAC_TERAHConnectionString {
            get {
                return ((string)(this["BD_SIAC_TERAHConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=190.40.59.201;Initial Catalog=BD_SIAC_TERAH;Persist Security Info=Tru" +
            "e;User ID=sa;Password=terahsiac")]
        public string BD_SIAC_TERAHConnectionString1 {
            get {
                return ((string)(this["BD_SIAC_TERAHConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=190.40.59.201;Initial Catalog=BD_SIAC_TERAH;Persist Security Info=Tru" +
            "e;User ID=sa;Password=terahsiac")]
        public string BD_SIAC_TERAHConnectionString2 {
            get {
                return ((string)(this["BD_SIAC_TERAHConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=190.40.59.201;Initial Catalog=BD_SIAC_TERAH;Persist Security Info=Tru" +
            "e;User ID=sa;Password=terahsiac")]
        public string BD_SIAC_TERAHConnectionString3 {
            get {
                return ((string)(this["BD_SIAC_TERAHConnectionString3"]));
            }
        }
    }
}
